/**
 * This file is auto-generated by scripts/build-tokens.mjs.
 * Do not edit this file directly.
 */
export const tokens = {
  "color": {
    "base": {
      "white": "#ffffff",
      "black": "#000000"
    },
    "neutral": {
      "0": "#ffffff",
      "10": "#f0f0f0",
      "20": "#e0e0e0",
      "40": "#999999",
      "60": "#666666",
      "70": "#666666",
      "90": "#333333",
      "100": "#f0f0f0",
      "200": "#e0e0e0",
      "400": "#999999",
      "600": "#666666",
      "700": "#374151",
      "800": "#1f2937",
      "900": "#0f172a",
      "00": "#ffffff",
      "05": "#f9f9f9"
    },
    "feedback": {
      "positive": "#4caf50",
      "negative": "#f44336",
      "negative-dark": "#d32f2f",
      "negative-darker": "#b71c1c",
      "warning": "#ff9800",
      "info": "#2196f3"
    },
    "action": {
      "default": "#0066cc",
      "hover": "#0052a3",
      "pressed": "#003d7a",
      "disabled": "#cccccc",
      "focus": "#0066cc"
    },
    "background": {
      "default": "#ffffff",
      "secondary": "#f8fafc",
      "hover": "#f1f5f9",
      "selected": "#e2e8f0",
      "dark": "#0f172a",
      "secondary-dark": "#1e293b"
    },
    "surface": {
      "default": "#ffffff",
      "subtle": "#f3f4f6",
      "muted": "#e2e8f0",
      "alt": "#cbd5f5",
      "disabled": "#f1f5f9",
      "hover": "#f8fafc",
      "readonly": "#f8fafc",
      "elevated": "#ffffff"
    },
    "muted": "#f8fafc",
    "disabled": "#cbd5f5",
    "text": {
      "default": "#111827",
      "primary": "#111827",
      "secondary": "#475569",
      "tertiary": "#64748b",
      "subtle": "#64748b",
      "placeholder": "#94a3b8",
      "disabled": "#94a3b8",
      "inverse": "#f8fafc",
      "primary-dark": "#f1f5f9",
      "secondary-dark": "#cbd5f5"
    },
    "foreground": "#0f172a",
    "border": {
      "default": "#d0d5dd",
      "light": "#e2e8f0",
      "subtle": "rgba(15, 23, 42, 0.08)",
      "hover": "#94a3b8",
      "disabled": "#e2e8f0",
      "dark": "#334155"
    },
    "primary": {
      "default": "#2563eb",
      "text": "#ffffff",
      "hover": "#1d4ed8",
      "active": "#1e40af",
      "light": "#60a5fa",
      "dark": "#1e3a8a",
      "contrast": "#ffffff",
      "alpha": "rgba(37, 99, 235, 0.16)",
      "subtle": "#dbeafe"
    },
    "secondary": {
      "default": "#6b7280",
      "text": "#1f2937",
      "hover": "#4b5563"
    },
    "tertiary": {
      "default": "#475569",
      "text": "#111827",
      "hover": "rgba(71, 85, 105, 0.08)"
    },
    "status": {
      "success": "#10b981",
      "warning": "#f59e0b",
      "info": "#0ea5e9",
      "error": "#ef4444",
      "error-hover": "#dc2626",
      "error-alpha": "rgba(239, 68, 68, 0.2)",
      "danger": "#dc2626",
      "danger-hover": "#b91c1c",
      "danger-active": "#991b1b",
      "danger-contrast": "#ffffff"
    },
    "interactive": {
      "focus-ring": "rgba(37, 99, 235, 0.35)",
      "primary-alpha-strong": "rgba(37, 99, 235, 0.24)"
    },
    "bg": "#ffffff",
    "bg-subtle": "#f3f4f6",
    "bg-hover": "#f1f5f9"
  },
  "motion": {
    "duration": {
      "instant": "80ms",
      "fast": "120ms",
      "normal": "200ms",
      "slow": "320ms",
      "deliberate": "480ms"
    },
    "timing": {
      "standard": "cubic-bezier(0.4, 0, 0.2, 1)",
      "entrance": "cubic-bezier(0.16, 1, 0.3, 1)",
      "exit": "cubic-bezier(0.4, 0, 0.6, 1)"
    },
    "transition": {
      "base": "all 0.2s ease-in-out",
      "fast": "0.15s ease",
      "normal": "0.2s ease-in-out",
      "slow": "0.3s ease-in-out"
    }
  },
  "spacing": {
    "xxs": "0.125rem",
    "xs": "0.25rem",
    "sm": "0.5rem",
    "md": "1rem",
    "lg": "1.5rem",
    "xl": "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
    "gutter": "1.5rem",
    "section": "3rem"
  },
  "typography": {
    "font": {
      "family": {
        "base": "'Inter', 'Segoe UI', system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif",
        "primary": "'Inter', 'Segoe UI', system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif",
        "mono": "'Fira Code', 'SFMono-Regular', Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
      },
      "size": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "md": "1.125rem",
        "lg": "1.25rem",
        "xl": "1.5rem",
        "2xl": "1.75rem"
      },
      "weight": {
        "normal": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700"
      }
    },
    "line": {
      "height": {
        "tight": "1.25",
        "normal": "1.5",
        "relaxed": "1.75"
      }
    },
    "letter": {
      "spacing": {
        "tight": "-0.01em",
        "normal": "0"
      }
    }
  }
} as const;

export type TokenCategories = keyof typeof tokens;
export type TokenGroup<K extends TokenCategories> = typeof tokens[K];

export const cssVariables = {
  "--dyn-color-action-default": "#0066cc",
  "--dyn-color-action-disabled": "#cccccc",
  "--dyn-color-action-focus": "#0066cc",
  "--dyn-color-action-hover": "#0052a3",
  "--dyn-color-action-pressed": "#003d7a",
  "--dyn-color-background-dark": "#0f172a",
  "--dyn-color-background-default": "#ffffff",
  "--dyn-color-background-hover": "#f1f5f9",
  "--dyn-color-background-secondary": "#f8fafc",
  "--dyn-color-background-secondary-dark": "#1e293b",
  "--dyn-color-background-selected": "#e2e8f0",
  "--dyn-color-base-black": "#000000",
  "--dyn-color-base-white": "#ffffff",
  "--dyn-color-bg": "#ffffff",
  "--dyn-color-bg-hover": "#f1f5f9",
  "--dyn-color-bg-subtle": "#f3f4f6",
  "--dyn-color-border-dark": "#334155",
  "--dyn-color-border-default": "#d0d5dd",
  "--dyn-color-border-disabled": "#e2e8f0",
  "--dyn-color-border-hover": "#94a3b8",
  "--dyn-color-border-light": "#e2e8f0",
  "--dyn-color-border-subtle": "rgba(15, 23, 42, 0.08)",
  "--dyn-color-disabled": "#cbd5f5",
  "--dyn-color-feedback-info": "#2196f3",
  "--dyn-color-feedback-negative": "#f44336",
  "--dyn-color-feedback-negative-dark": "#d32f2f",
  "--dyn-color-feedback-negative-darker": "#b71c1c",
  "--dyn-color-feedback-positive": "#4caf50",
  "--dyn-color-feedback-warning": "#ff9800",
  "--dyn-color-foreground": "#0f172a",
  "--dyn-color-interactive-focus-ring": "rgba(37, 99, 235, 0.35)",
  "--dyn-color-interactive-primary-alpha-strong": "rgba(37, 99, 235, 0.24)",
  "--dyn-color-muted": "#f8fafc",
  "--dyn-color-neutral-0": "#ffffff",
  "--dyn-color-neutral-00": "#ffffff",
  "--dyn-color-neutral-05": "#f9f9f9",
  "--dyn-color-neutral-10": "#f0f0f0",
  "--dyn-color-neutral-100": "#f0f0f0",
  "--dyn-color-neutral-20": "#e0e0e0",
  "--dyn-color-neutral-200": "#e0e0e0",
  "--dyn-color-neutral-40": "#999999",
  "--dyn-color-neutral-400": "#999999",
  "--dyn-color-neutral-60": "#666666",
  "--dyn-color-neutral-600": "#666666",
  "--dyn-color-neutral-70": "#666666",
  "--dyn-color-neutral-700": "#374151",
  "--dyn-color-neutral-800": "#1f2937",
  "--dyn-color-neutral-90": "#333333",
  "--dyn-color-neutral-900": "#0f172a",
  "--dyn-color-primary-active": "#1e40af",
  "--dyn-color-primary-alpha": "rgba(37, 99, 235, 0.16)",
  "--dyn-color-primary-contrast": "#ffffff",
  "--dyn-color-primary-dark": "#1e3a8a",
  "--dyn-color-primary-default": "#2563eb",
  "--dyn-color-primary-hover": "#1d4ed8",
  "--dyn-color-primary-light": "#60a5fa",
  "--dyn-color-primary-subtle": "#dbeafe",
  "--dyn-color-primary-text": "#ffffff",
  "--dyn-color-secondary-default": "#6b7280",
  "--dyn-color-secondary-hover": "#4b5563",
  "--dyn-color-secondary-text": "#1f2937",
  "--dyn-color-status-danger": "#dc2626",
  "--dyn-color-status-danger-active": "#991b1b",
  "--dyn-color-status-danger-contrast": "#ffffff",
  "--dyn-color-status-danger-hover": "#b91c1c",
  "--dyn-color-status-error": "#ef4444",
  "--dyn-color-status-error-alpha": "rgba(239, 68, 68, 0.2)",
  "--dyn-color-status-error-hover": "#dc2626",
  "--dyn-color-status-info": "#0ea5e9",
  "--dyn-color-status-success": "#10b981",
  "--dyn-color-status-warning": "#f59e0b",
  "--dyn-color-surface-alt": "#cbd5f5",
  "--dyn-color-surface-default": "#ffffff",
  "--dyn-color-surface-disabled": "#f1f5f9",
  "--dyn-color-surface-elevated": "#ffffff",
  "--dyn-color-surface-hover": "#f8fafc",
  "--dyn-color-surface-muted": "#e2e8f0",
  "--dyn-color-surface-readonly": "#f8fafc",
  "--dyn-color-surface-subtle": "#f3f4f6",
  "--dyn-color-tertiary-default": "#475569",
  "--dyn-color-tertiary-hover": "rgba(71, 85, 105, 0.08)",
  "--dyn-color-tertiary-text": "#111827",
  "--dyn-color-text-default": "#111827",
  "--dyn-color-text-disabled": "#94a3b8",
  "--dyn-color-text-inverse": "#f8fafc",
  "--dyn-color-text-placeholder": "#94a3b8",
  "--dyn-color-text-primary": "#111827",
  "--dyn-color-text-primary-dark": "#f1f5f9",
  "--dyn-color-text-secondary": "#475569",
  "--dyn-color-text-secondary-dark": "#cbd5f5",
  "--dyn-color-text-subtle": "#64748b",
  "--dyn-color-text-tertiary": "#64748b",
  "--dyn-spacing-2xl": "3rem",
  "--dyn-spacing-3xl": "4rem",
  "--dyn-spacing-gutter": "1.5rem",
  "--dyn-spacing-lg": "1.5rem",
  "--dyn-spacing-md": "1rem",
  "--dyn-spacing-section": "3rem",
  "--dyn-spacing-sm": "0.5rem",
  "--dyn-spacing-xl": "2rem",
  "--dyn-spacing-xs": "0.25rem",
  "--dyn-spacing-xxs": "0.125rem",
  "--dyn-font-family-base": "'Inter', 'Segoe UI', system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif",
  "--dyn-font-family-mono": "'Fira Code', 'SFMono-Regular', Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  "--dyn-font-family-primary": "'Inter', 'Segoe UI', system-ui, -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif",
  "--dyn-font-size-2xl": "1.75rem",
  "--dyn-font-size-base": "1rem",
  "--dyn-font-size-lg": "1.25rem",
  "--dyn-font-size-md": "1.125rem",
  "--dyn-font-size-sm": "0.875rem",
  "--dyn-font-size-xl": "1.5rem",
  "--dyn-font-size-xs": "0.75rem",
  "--dyn-font-weight-bold": "700",
  "--dyn-font-weight-medium": "500",
  "--dyn-font-weight-normal": "400",
  "--dyn-font-weight-semibold": "600",
  "--dyn-letter-spacing-normal": "0",
  "--dyn-letter-spacing-tight": "-0.01em",
  "--dyn-line-height-normal": "1.5",
  "--dyn-line-height-relaxed": "1.75",
  "--dyn-line-height-tight": "1.25",
  "--dyn-duration-deliberate": "480ms",
  "--dyn-duration-fast": "120ms",
  "--dyn-duration-instant": "80ms",
  "--dyn-duration-normal": "200ms",
  "--dyn-duration-slow": "320ms",
  "--dyn-timing-entrance": "cubic-bezier(0.16, 1, 0.3, 1)",
  "--dyn-timing-exit": "cubic-bezier(0.4, 0, 0.6, 1)",
  "--dyn-timing-standard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "--dyn-transition-base": "all 0.2s ease-in-out",
  "--dyn-transition-fast": "0.15s ease",
  "--dyn-transition-normal": "0.2s ease-in-out",
  "--dyn-transition-slow": "0.3s ease-in-out"
} as const;

export type CssVariableName = keyof typeof cssVariables;

export function buildCssCustomProperties(selector = ':root') {
  const declarations = Object.entries(cssVariables)
    .map(([name, value]) => '  ' + name + ': ' + value + ';');
  return selector + ' {\n' + declarations.join('\n') + '\n}';
}

export function tokenVar(name) {
  return 'var(' + name + ')';
}
