name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.11.1'

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write
  pages: write

jobs:
  changesets:
    name: Release packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Changesets release
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run release:version
          publish: pnpm run release:publish
          commit: chore: release packages
          title: chore: release packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}

  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: changesets
    if: needs.changesets.outputs.published == 'true'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Storybook
        run: pnpm run build-storybook
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    needs: changesets
    if: needs.changesets.outputs.has_changesets == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate changelog summary
        run: pnpm run changelog:generate
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-changelog
          path: reports/changelog
          if-no-files-found: warn
