name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
     # - name: Install browsers
     #   run: pnpm exec playwright install --with-deps
    #  - name: Run Playwright E2E tests
        #run: pnpm exec playwright test
